# Generated by Django 3.2.6 on 2021-08-09 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=5)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('Running out', 'Running out'), ('Sold out', 'Sold out'), ('Available', 'Available')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ManyToManyField(to='api.Category')),
            ],
        ),
    ]
