# Generated by Django 3.2.6 on 2021-08-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
    ]
